//throw -- menangkap error
/*
let x = 1;
if(x < 0) throw new Error('X must be positive, not negative value');
console.log(x);
*/

//try/catch/finally
try{
    myFunction();
}catch(error){
    // console.log('Terjadi kesalahan: ' + error.message / error.name);
    // console.log(error);

}